# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 047f9733808cbfafdf6f1e6a8fd82148ec60fdd266086460bea876257d1d164cf9aaae742e41743d5bd1e71165c90ad21cf2d1983f9a1ff027982bcb0de51305

test:
  secret_key_base: 34328132ab33fa6624338b9d57436183ded51460ea5a600e8316821d96746024da9111bf6e3a49a05c1216b2982b5fa9d4302fc0f881e0eb4264164c7ac7fbaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
